// for(let i=0;i<=100;i++)
// {  if(i%2===0)
// {
//     console.log(i)
// }
   
// }


//
// <!DOCTYPE html>
// <html lang="en">
// <head>
//     <meta charset="UTF-8">
//     <meta name="viewport" content="width=device-width, initial-scale=1.0">
//     <title>Document</title>
// </head>
// <body>
//     <script>
//         let Full_name=prompt("enter your full name without spaces")
//         let username="@"+Full_name+Full_name.length
//         document.write(username)
//     </script>
// </body>
// </html>